{% set name = "detectron2" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8026519973eb0b670d8fb59ece15fbf70945ffbaa71e3f409c47e009235ab288

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pytorch >=1.4
  run:
    - python
    - cloudpickle
    - future
    - fvcore
    - matplotlib-base
    - pillow
    - pycocotools
    - pydot
    - tensorboard
    - termcolor >=1.1
    - tqdm >4.29.0
    - yacs >=0.1.6

test:
  imports:
    - detectron2
  requires:
    - black ==19.3b0
    - flake8
    - flake8-bugbear
    - flake8-comprehensions
    - isort
    - pytorch

about:
  home: https://github.com/facebookresearch/detectron2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Detectron2 is FAIR's next-generation platform for object detection and segmentation.
  doc_url: https://github.com/facebookresearch/detectron2
  dev_url: https://github.com/facebookresearch/detectron2

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
