{% set name = "detectron2" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1294603f48ccb1d31b6c540233c724e392257643f378755fc688de0b57e823b3

build:
  number: 3
  skip: true                                 # [win]
  script: {{ PYTHON }} -m pip install . -vv
  
  missing_dso_whitelist:
    - "$RPATH/libc10.so"
    - "$RPATH/libtorch_cpu.so"
    - "$RPATH/libtorch_python.so"
    - /lib/libstdc++.so.6
    - /lib*/libgcc_s.so.1
    - /lib*/libc.so.6

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version not in (undefined, 'None')]
  host:
    - python
    - pip
    - pytorch-cpu                            # [osx or cuda_compiler_version in (undefined, 'None')]
    - pytorch-gpu                            # [cuda_compiler_version not in (undefined, 'None')]
  run:
    - python
    - cloudpickle
    - future
    - fvcore
    - matplotlib-base
    - pillow
    - pycocotools
    - pydot
    - tensorboard
    - termcolor >=1.1
    - tqdm >4.29.0
    - yacs >=0.1.6

    - {{ pin_compatible('pytorch-cpu') }}    # [osx or cuda_compiler_version in (undefined, 'None')]
    - {{ pin_compatible('pytorch-gpu') }}    # [cuda_compiler_version not in (undefined, 'None')]

test:
  imports:
    - detectron2
  requires:
    - black ==21.4b2
    - flake8
    - flake8-bugbear
    - flake8-comprehensions
    - isort
    - pytorch

about:
  home: https://github.com/facebookresearch/detectron2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Detectron2 is FAIR's next-generation platform for object detection and segmentation.
  doc_url: https://github.com/facebookresearch/detectron2
  dev_url: https://github.com/facebookresearch/detectron2

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - benjaminrwilson
