{% set name = "detectron2" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9757fed05fa32acc2116ea038185f08409d5e854573e70f41909a358b70d1004

build:
  number: 1
  skip: true  # [win or pytorch == "1.10.*" and (cuda_compiler_version == "10.1") or pytorch == "1.9.*" and (cuda_compiler_version == "11.3" or cuda_compiler_version == "10.1") or pytorch == "1.8.*" and cuda_compiler_version == "11.3"]
    
  string: torch{{ pytorch | replace('.', '') | replace('*', '') }}_cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: torch{{ pytorch | replace('.', '') | replace('*', '') }}_cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                                 # [cuda_compiler_version == "None"]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}      # [cuda_compiler_version != "None"]
  host:
    - python
    - pip
    - pytorch-gpu {{ pytorch }}      # [cuda_compiler_version != "None"]
    - pytorch-cpu {{ pytorch }}      # [cuda_compiler_version == "None"]
  run:
    - python
    - {{ pin_compatible('pytorch-gpu', min_pin='x.x.x', max_pin='x.x') }}                  # [cuda_compiler_version != "None"]
    - {{ pin_compatible('pytorch-cpu', min_pin='x.x.x', max_pin='x.x') }}                  # [cuda_compiler_version == "None"]    
    - pillow >=7.1
    - matplotlib-base
    - pycocotools >=2.0.2
    - termcolor >=1.1    
    - cloudpickle
    - tqdm >4.29.0
    - tensorboard
    - fvcore >=0.1.5,<0.1.6
    - iopath >=0.1.7,<0.1.10
    - future    
    - pydot
    - omegaconf >=2.1
    - hydra-core >=1.1
    - yacs >=0.1.8
    - torchvision

test:
  imports:
    - detectron2
    - detectron2.model_zoo
  requires:
    - black ==21.4b2
    - flake8 ==3.8.1
    - flake8-bugbear
    - flake8-comprehensions
    - isort

about:
  home: https://github.com/facebookresearch/detectron2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Detectron2 is FAIR's next-generation platform for object detection and segmentation.
  doc_url: https://github.com/facebookresearch/detectron2
  dev_url: https://github.com/facebookresearch/detectron2

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - baszalmstra
