{% set version = "0.6" %}

# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: detectron2
  version: {{ version }}

source:
  url: https://github.com/facebookresearch/detectron2/archive/v{{ version }}.tar.gz
  sha256: 9757fed05fa32acc2116ea038185f08409d5e854573e70f41909a358b70d1004
  patches:
    - 0001-Monkeypatch-TORCH_LIB_PATH.patch
    - ff53992b1985b63bd3262b5a36167098e3dada02.patch

build:
  number: 15
  skip: true  # [win]
  skip: true  # [aarch64 and cuda_compiler_version != "None"]
  # pytorch in conda-forge does not support CUDA 11.8 as of v2.5
  skip: true  # [cuda_compiler_version == "11.8"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                                # [cuda_compiler_version == "None"]
  run_exports:
    # ensure matching proc-type
    - torchvision =*={{ torch_proc_type }}*

requirements:
  build:
    - python                                         # [build_platform != target_platform]
    - cross-python_{{ target_platform }}             # [build_platform != target_platform]
    - pytorch ={{ pytorch }}={{ torch_proc_type }}*  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}      # [cuda_compiler_version != "None"]
  host:
    - python
    - pip
    - pytorch
    - pytorch =*={{ torch_proc_type }}*
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - libcublas-dev     # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev   # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev   # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - pillow >=7.1
    - matplotlib-base
    - pycocotools >=2.0.2
    - termcolor >=1.1    
    - cloudpickle
    - tqdm >4.29.0
    - tensorboard
    - fvcore >=0.1.5,<0.1.6
    - iopath >=0.1.7,<0.1.10
    - future    
    - pydot
    - omegaconf >=2.1
    - hydra-core >=1.1
    - yacs >=0.1.8
    - torchvision
  run_constrained:
    # additional run constraint to the one from the (version-only) run_export;
    # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
    - pytorch =*={{ torch_proc_type }}*
    - torchvision =*=cuda{{ cuda_compiler_version | replace('.', '') }}*  # [cuda_compiler_version != "None"]

test:
  imports:
    - detectron2
    - detectron2.model_zoo
  source_files:
    - tests/**
    - datasets/**
  requires:
    - opencv
  commands:
    # Run a basic set of tests to check for version compatability.
    # Sadly not all of them run in our limited CI infrastructure.
    # Skip older pytorch versions which aren't fully compatible with torchvision.
    - python -m unittest discover -v -s ./tests/layers

about:
  home: https://github.com/facebookresearch/detectron2
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Detectron2 is FAIR's next-generation platform for object detection and segmentation.
  doc_url: https://github.com/facebookresearch/detectron2
  dev_url: https://github.com/facebookresearch/detectron2

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
    - baszalmstra
    - xhochy
